### PR TITLE
feat: rest db service

### PR DESCRIPTION
**Pull request by grantmacken**
issue #53 
enables rest interaction with xqerl db collections and XDM items

Uses cowboy rest handlers in conjunction with xQuery main modules,
to allow CRUD ops on xqerl database collections and items.

HTTP request methods that  create, list, retrieve, delete xqerl db  collection items 
POST collection URI with request body and ''content-type'  header and optional Slug **creates** a resource  
GET  collection URI  **lists** collection resources
GET resource URI with accept'  header **retrieves** serialized XDM item
PUT resource  URI with request body **updates** resource
DELETE resource URI **deletes** resource 
DELETE collection URI **deletes** all resources in collection
HEAD resource URI,  determine if  resource **available**. If available will return content-length header
HEAD collection URI, determine if collection **available**. 
OPTIONS collection URI, **allowable methods** for collection. 

checks: Curl is used to to check correct responses to HTTP requests
https://github.com/grantmacken/xqerl/actions/runs/1603743140

### CODE REVIEW

**Comment by zadean** [comment]
I've merged the last 2 PRs so this one is in conflict in a few places. Might need a rebase.

I've tried out what is done so far, and must say, Very cool!! :-)

**Comment by grantmacken** [comment]
@zadean thanks and best wishes for the season.. I am away over Xmas  new year period, will start looking at this again in a couple of weeks.

**Comment by zadean** [comment]
Great! Sounds good. Enjoy the time!

**Comment by grantmacken** [comment]
two issues, I don't think are there yet
1. A Head request should return content-length. I am not sure if this is achievable outside of  the static handler context.
2. The collection path should be  variadic  [...]  much like the static handler route allows. A the mo I only allow for a collection one level deep.

**Comment by grantmacken** [comment]
closing this as work on this on new branch 
 ref #58

**Pull request closed without merging**
