### PR TITLE
add priv/bin for users escripts

### PR DESCRIPTION
**Pull request by grantmacken**
Following the convention over configuration principle 
I think it would be nice to have a place to plonk escripts.

https://www.erlang.org/doc/design_principles/applications.html#id80846
> priv/bin - Recommended. Any executable that is used by the application, s

--------------------------------

 - [x] create priv/bin dir, add example escripts 
   - priv/bin/list-libs
   - priv/bin/list-db-uri

 - [x]  checks:(feat.yml)  xqerl escript on running instance
 ```
xqerl escript priv/bin/list-libs
xqerl escript priv/bin/list-db-uri
```
 - [x]  checks:(feat.yml)  as shebang executable escript 
 ```
pushd ~/.local/xqerl/priv/bin/
chmod +x ./list-db-uri
./list-db-uri
popd
```
 - [x]  checks:(feat.yml)  callable  executable on PATH 
 ```
ln -sf ~/.local/xqerl/priv/bin/list-db-uri ~/.local/bin/xqerl-list-db-uri
echo $PATH
# escript now callable from anywhere
xqerl-list-db-uri
```

--------------------------------

### CODE REVIEW

**Comment by grantmacken** [comment]
Here is the gh actions run 
https://github.com/grantmacken/xqerl/actions/runs/3149052293/jobs/5120250351#logs%E2%86%B4

It should also run here on a pull request. I'll look into why it doesn't

**Comment by grantmacken** [comment]
added a commit to run on pull request
https://github.com/zadean/xqerl/actions/runs/3155029179/jobs/5133567621

It too 30 min to run ? Hope it is a gh glitch
Will add timeout and stop it running twice

**Comment by grantmacken** [comment]
ok!  run on pr sync now
build and checks run under 5min
https://github.com/zadean/xqerl/actions/runs/3155272551

**Comment by zadean** [comment]
Nice! 👍🏼

**Pull request merged**
